import { MenuItem } from './models/menu.model'

export const MENU: MenuItem[] = [
  {
    key: 'navigation',
    label: 'navigation',
    isTitle: true,
  },
  {
    key: 'dashboards',
    icon: 'uil-home-alt',
    label: 'dashboards',
    collapsed: false,
    badge: { variant: 'success', text: '5' },
    subMenu: [
      {
        key: 'ds-analytics',
        label: 'analytics',
        link: '/dashboard-analytics',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-ecommerce',
        label: 'ecommerce',
        link: '/',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-project',
        label: 'projects',
        link: '/dashboard-projects',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-crm',
        label: 'crm',
        link: '/dashboard-crm',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-ewallet',
        label: 'e-Wallet',
        link: '/dashboard-wallet',
        parentKey: 'dashboards',
      },
    ],
  },
  {
    key: 'apps',
    label: 'apps',
    isTitle: true,
  },
  {
    key: 'apps-calendar',
    icon: 'uil-calender',
    label: 'calendar',
    link: '/apps-calendar',
  },
  {
    key: 'apps-chat',
    icon: 'uil-comments-alt',
    label: 'chat',
    link: '/apps-chat',
  },
  {
    key: 'apps-crm',
    icon: 'uil uil-tachometer-fast',
    label: 'crm',
    collapsed: true,
    badge: { variant: 'danger', text: 'New' },
    subMenu: [
      {
        key: 'crm-projects',
        label: 'projects',
        link: '/crm-projects',
        parentKey: 'apps-crm',
      },
      {
        key: 'crm-orderslist',
        label: 'orderslist',
        link: '/crm-orders-list',
        parentKey: 'apps-crm',
      },
      {
        key: 'crm-clients',
        label: 'clients',
        link: '/crm-clients',
        parentKey: 'apps-crm',
      },
      {
        key: 'crm-management',
        label: 'management',
        link: '/crm-management',
        parentKey: 'apps-crm',
      },
    ],
  },
  {
    key: 'apps-ecommerce',
    icon: 'uil-store',
    label: 'ecommerce',
    collapsed: true,
    subMenu: [
      {
        key: 'ecommerce-products',
        label: 'products',
        link: '/apps-ecommerce-products',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-productsdetails',
        label: 'productsdetails',
        link: '/apps-ecommerce-products-details',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-orders',
        label: 'orders',
        link: '/apps-ecommerce-orders',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-orderdetails',
        label: 'orderdetails',
        link: '/apps-ecommerce-orders-details',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-customers',
        label: 'customers',
        link: '/apps-ecommerce-customers',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-shoppingcart',
        label: 'shoppingcart',
        link: '/apps-ecommerce-shopping-cart',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-checkout',
        label: 'checkout',
        link: '/apps-ecommerce-checkout',
        parentKey: 'apps-ecommerce',
      },
      {
        key: 'ecommerce-sellers',
        label: 'sellers',
        link: '/apps-ecommerce-sellers',
        parentKey: 'apps-ecommerce',
      },
    ],
  },
  {
    key: 'apps-email',
    icon: 'uil-envelope',
    label: 'email',
    collapsed: true,
    subMenu: [
      {
        key: 'email-inbox',
        label: 'inbox',
        link: '/apps-email-inbox',
        parentKey: 'apps-email',
      },
      {
        key: 'email-read-email',
        label: 'reademail',
        link: '/apps-email-read',
        parentKey: 'apps-email',
      },
    ],
  },
  {
    key: 'apps-projects',
    icon: 'uil-briefcase',
    label: 'projects',
    collapsed: true,
    subMenu: [
      {
        key: 'projects-list',
        label: 'list',
        link: '/apps-projects-list',
        parentKey: 'apps-projects',
      },
      {
        key: 'projects-details',
        label: 'details',
        link: '/apps-projects-details',
        parentKey: 'apps-projects',
      },
      {
        key: 'projects-gantt',
        label: 'gantt',
        link: '/apps-projects-gantt',
        badge: { variant: 'light text-dark', text: 'New' },
        parentKey: 'apps-projects',
      },
      {
        key: 'projects-createproject',
        label: 'createproject',
        link: '/apps-projects-add',
        parentKey: 'apps-projects',
      },
    ],
  },
  {
    key: 'apps-social',
    icon: 'uil-rss',
    label: 'socialfeed',
    link: '/apps-social-feed',
  },
  {
    key: 'apps-tasks',
    icon: 'uil-clipboard-alt',
    label: 'tasks',
    collapsed: true,
    subMenu: [
      {
        key: 'tasks-list',
        label: 'list',
        link: '/apps-tasks',
        parentKey: 'apps-tasks',
      },
      {
        key: 'tasks-details',
        label: 'details',
        link: '/apps-tasks-details',
        parentKey: 'apps-tasks',
      },
      {
        key: 'tasks-kanbanboard',
        label: 'kanbanboard',
        link: '/apps-tasks-kanban',
        parentKey: 'apps-tasks',
      },
    ],
  },
  {
    key: 'apps-file-manager',
    icon: 'uil-folder-plus',
    label: 'filemanager',
    link: '/apps-file-manager',
  },
  {
    key: 'custom',
    label: 'custom',
    isTitle: true,
  },
  {
    key: 'pages',
    label: 'pages',
    isTitle: false,
    icon: 'uil-copy-alt',
    collapsed: true,
    subMenu: [
      {
        key: 'page-profile',
        label: 'profile',
        link: '/pages-profile',
        parentKey: 'pages',
      },
      {
        key: 'page-profile2',
        label: 'profile2',
        link: '/pages-profile-2',
        parentKey: 'pages',
      },
      {
        key: 'page-invoice',
        label: 'invoice',
        link: '/pages-invoice',
        parentKey: 'pages',
      },
      {
        key: 'page-faq',
        label: 'faq',
        link: '/pages-faq',
        parentKey: 'pages',
      },
      {
        key: 'page-pricing',
        label: 'pricing',
        link: '/pages-pricing',
        parentKey: 'pages',
      },
      {
        key: 'page-maintenance',
        label: 'maintenance',
        link: '/pages-maintenance',
        parentKey: 'pages',
      },
      {
        key: 'page-authentication',
        label: 'authentication',
        parentKey: 'pages',
        collapsed: true,
        subMenu: [
          {
            key: 'login',
            label: 'login',
            link: '/pages-login',
            parentKey: 'page-authentication',
          },
          {
            key: 'login2',
            label: 'login2',
            link: '/pages-login-2',
            parentKey: 'page-authentication',
          },
          {
            key: 'register',
            label: 'register',
            link: '/pages-register',
            parentKey: 'page-authentication',
          },
          {
            key: 'register2',
            label: 'register2',
            link: '/pages-register-2',
            parentKey: 'page-authentication',
          },
          {
            key: 'logout',
            label: 'logout',
            link: '/pages-logout',
            parentKey: 'page-authentication',
          },
          {
            key: 'logout2',
            label: 'logout2',
            link: '/pages-logout-2',
            parentKey: 'page-authentication',
          },
          {
            key: 'recoverpass',
            label: 'recoverpassword',
            link: '/pages-recoverpw',
            parentKey: 'page-authentication',
          },
          {
            key: 'recoverpass2',
            label: 'recoverpassword2',
            link: '/pages-recoverpw-2',
            parentKey: 'page-authentication',
          },
          {
            key: 'lockscreen',
            label: 'lockscreen',
            link: '/pages-lock-screen',
            parentKey: 'page-authentication',
          },
          {
            key: 'lockscreen2',
            label: 'lockscreen2',
            link: '/pages-lock-screen-2',
            parentKey: 'page-authentication',
          },
          {
            key: 'confirmmail',
            label: 'confirmmail',
            link: '/pages-confirm-mail',
            parentKey: 'page-authentication',
          },
          {
            key: 'confirmmail2',
            label: 'confirmmail2',
            link: '/pages-confirm-mail-2',
            parentKey: 'page-authentication',
          },
        ],
      },
      {
        key: 'page-error',
        label: 'error',
        parentKey: 'pages',
        collapsed: true,
        subMenu: [
          {
            key: 'page-error-404',
            label: 'error-404',
            link: '/pages-404',
            parentKey: 'page-error',
          },
          {
            key: 'page-error-404-alt',
            label: 'error-404-alt',
            link: '/pages-404-alt',
            parentKey: 'page-error',
          },
          {
            key: 'page-error-500',
            label: 'error-500',
            link: '/pages-500',
            parentKey: 'page-error',
          },
        ],
      },
      {
        key: 'page-starter',
        label: 'starter',
        link: '/pages-starter',
        parentKey: 'pages',
      },
      {
        key: 'page-preloader',
        label: 'preloader',
        link: '/pages-preloader',
        parentKey: 'pages',
      },
      {
        key: 'page-timeline',
        label: 'timeline',
        link: '/pages-timeline',
        parentKey: 'pages',
      },
    ],
  },
  {
    key: 'landing',
    label: 'landing',
    isTitle: false,
    icon: 'uil-globe',
    link: '/landing',
    badge: { variant: 'secondary', text: 'New' },
  },
  {
    key: 'components',
    label: 'components',
    isTitle: true,
  },
  {
    key: 'base-ui',
    icon: 'uil-box',
    label: 'baseUI',
    collapsed: true,
    subMenu: [
      {
        key: 'base-ui-accordions',
        label: 'accordions',
        link: '/ui-accordions',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-alerts',
        label: 'alerts',
        link: '/ui-alerts',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-avatars',
        label: 'avatars',
        link: '/ui-avatars',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-badges',
        label: 'badges',
        link: '/ui-badges',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-breadcrumb',
        label: 'breadcrumb',
        link: '/ui-breadcrumb',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-buttons',
        label: 'buttons',
        link: '/ui-buttons',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-cards',
        label: 'cards',
        link: '/ui-cards',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-carousel',
        label: 'carousel',
        link: '/ui-carousel',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-dropdowns',
        label: 'dropdowns',
        link: '/ui-dropdowns',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-video',
        label: 'video',
        link: '/ui-embed-video',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-grid',
        label: 'grid',
        link: '/ui-grid',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-listgroup',
        label: 'listgroup',
        link: '/ui-list-group',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-modals',
        label: 'modals',
        link: '/ui-modals',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-notifications',
        label: 'notifications',
        link: '/ui-notifications',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-offcanvas',
        label: 'offcanvas',
        link: '/ui-offcanvas',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-placeholders',
        label: 'placeholders',
        link: '/ui-placeholders',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-pagination',
        label: 'pagination',
        link: '/ui-pagination',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-popovers',
        label: 'popovers',
        link: '/ui-popovers',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-progress',
        label: 'progress',
        link: '/ui-progress',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-ribbons',
        label: 'ribbons',
        link: '/ui-ribbons',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-spinners',
        label: 'spinners',
        link: '/ui-spinners',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-tabs',
        label: 'tabs',
        link: '/ui-tabs',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-tooltips',
        label: 'tooltips',
        link: '/ui-tooltips',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-links',
        label: 'links',
        link: '/ui-links',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-typography',
        label: 'typography',
        link: '/ui-typography',
        parentKey: 'base-ui',
      },
      {
        key: 'base-ui-utilities',
        label: 'utilities',
        link: '/ui-utilities',
        parentKey: 'base-ui',
      },
    ],
  },
  {
    key: 'extended-ui',
    icon: 'uil-package',
    label: 'extendedUI',
    collapsed: true,
    subMenu: [
      {
        key: 'extended-ui-dragula',
        label: 'dragula',
        link: '/extended-dragula',
        parentKey: 'extended-ui',
      },
      {
        key: 'extended-ui-rangeslider',
        label: 'rangeslider',
        link: '/extended-range-slider',
        parentKey: 'extended-ui',
      },
      {
        key: 'extended-ui-ratings',
        label: 'ratings',
        link: '/extended-ratings',
        parentKey: 'extended-ui',
      },
      {
        key: 'extended-ui-scrollbar',
        label: 'scrollbar',
        link: '/extended-scrollbar',
        parentKey: 'extended-ui',
      },
      {
        key: 'extended-ui-scrollspy',
        label: 'scrollspy',
        link: '/extended-scrollspy',
        parentKey: 'extended-ui',
      },
    ],
  },
  {
    key: 'widgets',
    icon: 'uil-layer-group',
    label: 'widgets',
    link: '/widgets',
  },
  {
    key: 'icons',
    icon: 'uil-streering',
    label: 'icons',
    collapsed: true,
    subMenu: [
      {
        key: 'icons-remix',
        label: 'remix',
        link: '/icons-remixicons',
        parentKey: 'icons',
      },
      {
        key: 'icons-material-design',
        label: 'material-design',
        link: '/icons-mdi',
        parentKey: 'icons',
      },
      {
        key: 'icons-unicons',
        label: 'unicons',
        link: '/icons-unicons',
        parentKey: 'icons',
      },
    ],
  },
  {
    key: 'Charts',
    icon: 'uil-chart',
    label: 'Charts',
    collapsed: true,
    subMenu: [
      {
        key: 'apexcharts',
        label: 'apexcharts',
        collapsed: true,
        parentKey: 'Charts',
        subMenu: [
          {
            key: 'apexcharts-area',
            label: 'area',
            link: '/charts-apex-area',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-bar',
            label: 'bar',
            link: '/charts-apex-bar',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-bubble',
            label: 'bubble',
            link: '/charts-apex-bubble',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-candlstick',
            label: 'candlstick',
            link: '/charts-apex-candlestick',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-column',
            label: 'column',
            link: '/charts-apex-column',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-heatmap',
            label: 'heatmap',
            link: '/charts-apex-heatmap',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-line',
            label: 'line',
            link: '/charts-apex-line',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-mixed',
            label: 'mixed',
            link: '/charts-apex-mixed',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-timeline',
            label: 'timeline',
            link: '/charts-apex-timeline',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-boxplot',
            label: 'boxplot',
            link: '/charts-apex-boxplot',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-treemap',
            label: 'treemap',
            link: '/charts-apex-treemap',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-pie',
            label: 'pie',
            link: '/charts-apex-pie',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-radar',
            label: 'radar',
            link: '/charts-apex-radar',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-radialbar',
            label: 'radialbar',
            link: '/charts-apex-radialbar',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-scatter',
            label: 'scatter',
            link: '/charts-apex-scatter',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-polar-area',
            label: 'polar-area',
            link: '/charts-apex-polar',
            parentKey: 'apexcharts',
          },
          {
            key: 'apexcharts-sparklines',
            label: 'sparklines',
            link: '/charts-apex-sparklines',
            parentKey: 'apexcharts',
          },
        ],
      },
      {
        key: 'chartJS',
        label: 'chartJS',
        collapsed: true,
        parentKey: 'Charts',
        subMenu: [
          {
            key: 'chartJS-area',
            label: 'area',
            link: '/charts-chartjs-area',
            parentKey: 'chartJS',
          },
          {
            key: 'chartJS-bar',
            label: 'bar',
            link: '/charts-chartjs-bar',
            parentKey: 'chartJS',
          },
          {
            key: 'chartJS-line',
            label: 'line',
            link: '/charts-chartjs-line',
            parentKey: 'chartJS',
          },
          {
            key: 'chartJS-other',
            label: 'other',
            link: '/charts-chartjs-other',
            parentKey: 'chartJS',
          },
        ],
      },
    ],
  },
  {
    key: 'forms',
    icon: 'uil-document-layout-center',
    label: 'forms',
    collapsed: true,
    subMenu: [
      {
        key: 'forms-basic-elements',
        label: 'basic-elements',
        link: '/form-elements',
        parentKey: 'forms',
      },
      {
        key: 'forms-advanced',
        label: 'form-advanced',
        link: '/form-advanced',
        parentKey: 'forms',
      },
      {
        key: 'forms-validation',
        label: 'validation',
        link: '/form-validation',
        parentKey: 'forms',
      },
      {
        key: 'forms-wizard',
        label: 'wizard',
        link: '/form-wizard',
        parentKey: 'forms',
      },
      {
        key: 'forms-file-uploads',
        label: 'file-uploads',
        link: '/form-fileuploads',
        parentKey: 'forms',
      },
      {
        key: 'forms-editors',
        label: 'editors',
        link: '/form-editors',
        parentKey: 'forms',
      },
    ],
  },
  {
    key: 'tables',
    icon: 'uil-table',
    label: 'tables',
    collapsed: true,
    subMenu: [
      {
        key: 'tables-basic',
        label: 'basic-tables',
        link: '/tables-basic',
        parentKey: 'tables',
      },
      {
        key: 'tables-datatables',
        label: 'datatables',
        link: '/tables-datatable',
        parentKey: 'tables',
      },
    ],
  },
  {
    key: 'maps',
    icon: 'uil-location-point',
    label: 'maps',
    collapsed: true,
    subMenu: [
      {
        key: 'maps-google',
        label: 'google',
        link: '/maps-google',
        parentKey: 'maps',
      },
      {
        key: 'maps-vector',
        label: 'vector',
        link: '/maps-vector',
        parentKey: 'maps',
      },
    ],
  },
  {
    key: 'multilevel',
    icon: 'uil-folder-plus',
    label: 'multilevel',
    collapsed: true,
    subMenu: [
      {
        key: 'secondlevel',
        label: 'secondlevel',
        collapsed: true,
        parentKey: 'multilevel',
        subMenu: [
          {
            key: 'item1',
            label: 'item-1',
            link: '',
            parentKey: 'secondlevel',
          },
          {
            key: 'item2',
            label: 'item-2',
            link: '',
            parentKey: 'secondlevel',
          },
        ],
      },
      {
        key: 'thirdlevel',
        label: 'thirdlevel',
        collapsed: true,
        parentKey: 'multilevel',
        subMenu: [
          {
            key: 'item1',
            label: 'item-1',
            link: '',
            parentKey: 'thirdlevel',
          },
          {
            key: 'item2',
            label: 'item-2',
            collapsed: true,
            parentKey: 'thirdlevel',
            subMenu: [
              {
                key: 'item2.1',
                label: 'item-2.1',
                link: '',
                parentKey: 'item2',
              },
              {
                key: 'item2.2',
                label: 'item-2.2',
                link: '',
                parentKey: 'item2',
              },
            ],
          },
        ],
      },
    ],
  },
]

export const HORIZONTAL_MENU: MenuItem[] = [
  {
    key: 'dashboards',
    icon: 'uil-dashboard',
    label: 'dashboards',
    collapsed: false,
    subMenu: [
      {
        key: 'ds-analytics',
        label: 'analytics',
        link: '/dashboard-analytics',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-ecommerce',
        label: 'ecommerce',
        link: '/',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-project',
        label: 'projects',
        link: '/dashboard-projects',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-crm',
        label: 'crm',
        link: '/dashboard-crm',
        parentKey: 'dashboards',
      },
      {
        key: 'ds-ewallet',
        label: 'e-Wallet',
        link: '/dashboard-wallet',
        parentKey: 'dashboards',
      },
    ],
  },
  {
    key: 'apps',
    icon: 'uil-apps',
    label: 'apps',
    collapsed: false,
    subMenu: [
      {
        key: 'apps-calendar',
        label: 'calendar',
        link: '/apps-calendar',
        parentKey: 'apps',
      },
      {
        key: 'apps-chat',
        label: 'chat',
        link: '/apps-chat',
        parentKey: 'apps',
      },
      {
        key: 'apps-crm',
        icon: 'uil uil-tachometer-fast',
        label: 'crm',
        collapsed: true,
        parentKey: 'apps',

        subMenu: [
          {
            key: 'crm-projects',
            label: 'projects',
            link: '/crm-projects',
            parentKey: 'apps-crm',
          },
          {
            key: 'crm-orderslist',
            label: 'orderslist',
            link: '/crm-orders-list',
            parentKey: 'apps-crm',
          },
          {
            key: 'crm-clients',
            label: 'clients',
            link: '/crm-clients',
            parentKey: 'apps-crm',
          },
          {
            key: 'crm-management',
            label: 'management',
            link: '/crm-management',
            parentKey: 'apps-crm',
          },
        ],
      },
      {
        key: 'apps-ecommerce',
        icon: 'uil-store',
        label: 'ecommerce',
        collapsed: true,
        subMenu: [
          {
            key: 'ecommerce-products',
            label: 'products',
            link: '/apps-ecommerce-products',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-productsdetails',
            label: 'productsdetails',
            link: '/apps-ecommerce-products-details',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-orders',
            label: 'orders',
            link: '/apps-ecommerce-orders',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-orderdetails',
            label: 'orderdetails',
            link: '/apps-ecommerce-orders-details',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-customers',
            label: 'customers',
            link: '/apps-ecommerce-customers',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-shoppingcart',
            label: 'shoppingcart',
            link: '/apps-ecommerce-shopping-cart',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-checkout',
            label: 'checkout',
            link: '/apps-ecommerce-checkout',
            parentKey: 'apps-ecommerce',
          },
          {
            key: 'ecommerce-sellers',
            label: 'sellers',
            link: '/apps-ecommerce-sellers',
            parentKey: 'apps-ecommerce',
          },
        ],
      },
      {
        key: 'apps-email',
        icon: 'uil-envelope',
        label: 'email',
        collapsed: true,
        subMenu: [
          {
            key: 'email-inbox',
            label: 'inbox',
            link: '/apps-email-inbox',
            parentKey: 'apps-email',
          },
          {
            key: 'email-read-email',
            label: 'reademail',
            link: '/apps-email-read',
            parentKey: 'apps-email',
          },
        ],
      },
      {
        key: 'apps-projects',
        icon: 'uil-briefcase',
        label: 'projects',
        collapsed: true,
        subMenu: [
          {
            key: 'projects-list',
            label: 'list',
            link: '/apps-projects-list',
            parentKey: 'apps-projects',
          },
          {
            key: 'projects-details',
            label: 'details',
            link: '/apps-projects-details',
            parentKey: 'apps-projects',
          },
          {
            key: 'projects-gantt',
            label: 'gantt',
            link: '/apps-projects-gantt',
            parentKey: 'apps-projects',
          },
          {
            key: 'projects-createproject',
            label: 'createproject',
            link: '/apps-projects-add',
            parentKey: 'apps-projects',
          },
        ],
      },
      {
        key: 'apps-social',
        icon: 'uil-rss',
        label: 'socialfeed',
        link: '/apps-social-feed',
      },
      {
        key: 'apps-tasks',
        icon: 'uil-clipboard-alt',
        label: 'tasks',
        collapsed: true,
        subMenu: [
          {
            key: 'tasks-list',
            label: 'list',
            link: '/apps-tasks',
            parentKey: 'apps-tasks',
          },
          {
            key: 'tasks-details',
            label: 'details',
            link: '/apps-tasks-details',
            parentKey: 'apps-tasks',
          },
          {
            key: 'tasks-kanbanboard',
            label: 'kanbanboard',
            link: '/apps-tasks-kanban',
            parentKey: 'apps-tasks',
          },
        ],
      },
      {
        key: 'apps-file-manager',
        icon: 'uil-folder-plus',
        label: 'filemanager',
        link: '/apps-file-manager',
      },
    ],
  },
  {
    key: 'pages',
    icon: 'uil-copy-alt',
    label: 'pages',
    collapsed: false,
    subMenu: [
      {
        key: 'page-authentication',
        label: 'authentication',
        parentKey: 'pages',
        subMenu: [
          {
            key: 'login',
            label: 'login',
            link: '/pages-login',
            parentKey: 'page-authentication',
          },
          {
            key: 'login2',
            label: 'login2',
            link: '/pages-login-2',
            parentKey: 'page-authentication',
          },
          {
            key: 'register',
            label: 'register',
            link: '/pages-register',
            parentKey: 'page-authentication',
          },
          {
            key: 'register2',
            label: 'register2',
            link: '/pages-register-2',
            parentKey: 'page-authentication',
          },
          {
            key: 'logout',
            label: 'logout',
            link: '/pages-logout',
            parentKey: 'page-authentication',
          },
          {
            key: 'logout2',
            label: 'logout',
            link: '/pages-logout-2',
            parentKey: 'page-authentication',
          },
          {
            key: 'recoverpass',
            label: 'recoverpassword',
            link: '/pages-recoverpw',
            parentKey: 'page-authentication',
          },
          {
            key: 'recoverpass2',
            label: 'recoverpassword2',
            link: '/pages-recoverpw-2',
            parentKey: 'page-authentication',
          },
          {
            key: 'lockscreen',
            label: 'lockscreen',
            link: '/pages-lock-screen',
            parentKey: 'page-authentication',
          },
          {
            key: 'lockscreen2',
            label: 'lockscreen2',
            link: '/pages-lock-screen-2',
            parentKey: 'page-authentication',
          },
          {
            key: 'confirmmail',
            label: 'confirmmail',
            link: '/pages-confirm-mail',
            parentKey: 'page-authentication',
          },
          {
            key: 'confirmmail2',
            label: 'confirmmail2',
            link: '/pages-confirm-mail-2',
            parentKey: 'page-authentication',
          },
        ],
      },
      {
        key: 'page-error',
        label: 'error',
        parentKey: 'pages',
        subMenu: [
          {
            key: 'page-error-404',
            label: 'error-404',
            link: '/pages-404',
            parentKey: 'page-error',
          },
          {
            key: 'page-error-404-alt',
            label: 'error-404-alt',
            link: '/pages-404-alt',
            parentKey: 'page-error',
          },
          {
            key: 'page-error-500',
            label: 'error-500',
            link: '/pages-500',
            parentKey: 'page-error',
          },
        ],
      },
      {
        key: 'page-starter',
        label: 'starter',
        link: '/pages-starter',
        parentKey: 'pages',
      },
      {
        key: 'page-preloader',
        label: 'preloader',
        link: '/pages-preloader',
        parentKey: 'pages',
      },
      {
        key: 'page-profile',
        label: 'profile',
        link: '/pages-profile',
        parentKey: 'pages',
      },
      {
        key: 'page-profile2',
        label: 'profile 2',
        link: '/pages-profile-2',
        parentKey: 'pages',
      },
      {
        key: 'page-invoice',
        label: 'invoice',
        link: '/pages-invoice',
        parentKey: 'pages',
      },
      {
        key: 'page-faq',
        label: 'faq',
        link: '/pages-faq',
        parentKey: 'pages',
      },
      {
        key: 'page-pricing',
        label: 'pricing',
        link: '/pages-pricing',
        parentKey: 'pages',
      },
      {
        key: 'page-maintenance',
        label: 'maintenance',
        link: '/pages-maintenance',
        parentKey: 'pages',
      },
      {
        key: 'page-timeline',
        label: 'timeline',
        link: '/pages-timeline',
        parentKey: 'pages',
      },
      {
        key: 'landing',
        label: 'landing',
        link: '/landing',
        parentKey: 'pages',
      },
    ],
  },
  {
    key: 'components',
    icon: 'uil-package',
    label: 'components',
    collapsed: true,
    subMenu: [
      {
        key: 'widgets',
        label: 'widgets',
        link: '/widgets',
        parentKey: 'components',
      },
      {
        key: 'base-ui',
        icon: 'uil-box',
        label: 'baseUI1',
        parentKey: 'components',
        collapsed: true,
        subMenu: [
          {
            key: 'base-ui-accordions',
            label: 'accordions',
            link: '/ui-accordions',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-alerts',
            label: 'alerts',
            link: '/ui-alerts',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-avatars',
            label: 'avatars',
            link: '/ui-avatars',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-badges',
            label: 'badges',
            link: '/ui-badges',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-breadcrumb',
            label: 'breadcrumb',
            link: '/ui-breadcrumb',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-buttons',
            label: 'buttons',
            link: '/ui-buttons',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-cards',
            label: 'cards',
            link: '/ui-cards',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-carousel',
            label: 'carousel',
            link: '/ui-carousel',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-dropdowns',
            label: 'dropdowns',
            link: '/ui-dropdowns',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-video',
            label: 'video',
            link: '/ui-embed-video',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-grid',
            label: 'grid',
            link: '/ui-grid',
            parentKey: 'base-ui',
          },
          {
            key: 'base-ui-listgroup',
            label: 'listgroup',
            link: '/ui-list-group',
            parentKey: 'base-ui',
          },
        ],
      },
      {
        key: 'base-ui2',
        icon: 'uil-box',
        label: 'baseUI2',
        collapsed: true,
        parentKey: 'components',
        subMenu: [
          {
            key: 'base-ui-modals',
            label: 'modals',
            link: '/ui-modals',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-notifications',
            label: 'notifications',
            link: '/ui-notifications',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-offcanvas',
            label: 'offcanvas',
            link: '/ui-offcanvas',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-placeholders',
            label: 'placeholders',
            link: '/ui-placeholders',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-pagination',
            label: 'pagination',
            link: '/ui-pagination',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-popovers',
            label: 'popovers',
            link: '/ui-popovers',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-progress',
            label: 'progress',
            link: '/ui-progress',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-ribbons',
            label: 'ribbons',
            link: '/ui-ribbons',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-spinners',
            label: 'spinners',
            link: '/ui-spinners',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-tabs',
            label: 'tabs',
            link: '/ui-tabs',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-tooltips',
            label: 'tooltips',
            link: '/ui-tooltips',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-links',
            label: 'links',
            link: '/ui-links',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-typography',
            label: 'typography',
            link: '/ui-typography',
            parentKey: 'base-ui2',
          },
          {
            key: 'base-ui-utilities',
            label: 'utilities',
            link: '/ui-utilities',
            parentKey: 'base-ui2',
          },
        ],
      },
      {
        key: 'extended-ui',
        icon: 'uil-package',
        label: 'extendedUI',
        collapsed: true,
        parentKey: 'components',
        subMenu: [
          {
            key: 'extended-ui-dragula',
            label: 'dragula',
            link: '/extended-dragula',
            parentKey: 'extended-ui',
          },
          {
            key: 'extended-ui-rangeslider',
            label: 'rangeslider',
            link: '/extended-range-slider',
            parentKey: 'extended-ui',
          },
          {
            key: 'extended-ui-ratings',
            label: 'ratings',
            link: '/extended-ratings',
            parentKey: 'extended-ui',
          },
          {
            key: 'extended-ui-scrollbar',
            label: 'scrollbar',
            link: '/extended-scrollbar',
            parentKey: 'extended-ui',
          },
          {
            key: 'extended-ui-scrollspy',
            label: 'scrollspy',
            link: '/extended-scrollspy',
            parentKey: 'extended-ui',
          },
        ],
      },
      {
        key: 'forms',
        icon: 'uil-document-layout-center',
        label: 'forms',
        collapsed: true,
        parentKey: 'components',
        subMenu: [
          {
            key: 'forms-basic-elements',
            label: 'basic-elements',
            link: '/form-elements',
            parentKey: 'forms',
          },
          {
            key: 'forms-advanced',
            label: 'form-advanced',
            link: '/form-advanced',
            parentKey: 'forms',
          },
          {
            key: 'forms-validation',
            label: 'validation',
            link: '/form-validation',
            parentKey: 'forms',
          },
          {
            key: 'forms-wizard',
            label: 'wizard',
            link: '/form-wizard',
            parentKey: 'forms',
          },
          {
            key: 'forms-file-uploads',
            label: 'file-uploads',
            link: '/form-fileuploads',
            parentKey: 'forms',
          },
          {
            key: 'forms-editors',
            label: 'editors',
            link: '/form-editors',
            parentKey: 'forms',
          },
        ],
      },
      {
        key: 'Charts',
        icon: 'uil-chart',
        label: 'Charts',
        collapsed: true,
        parentKey: 'components',
        subMenu: [
          {
            key: 'apexcharts',
            label: 'apexcharts',
            collapsed: true,
            parentKey: 'Charts',
            subMenu: [
              {
                key: 'apexcharts-area',
                label: 'area',
                link: '/charts-apex-area',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-bar',
                label: 'bar',
                link: '/charts-apex-bar',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-bubble',
                label: 'bubble',
                link: '/charts-apex-bubble',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-candlstick',
                label: 'candlstick',
                link: '/charts-apex-candlestick',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-column',
                label: 'column',
                link: '/charts-apex-column',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-heatmap',
                label: 'heatmap',
                link: '/charts-apex-heatmap',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-line',
                label: 'line',
                link: '/charts-apex-line',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-mixed',
                label: 'mixed',
                link: '/charts-apex-mixed',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-timeline',
                label: 'timeline',
                link: '/charts-apex-timeline',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-boxplot',
                label: 'boxplot',
                link: '/charts-apex-boxplot',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-treemap',
                label: 'treemap',
                link: '/charts-apex-treemap',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-pie',
                label: 'pie',
                link: '/charts-apex-pie',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-radar',
                label: 'radar',
                link: '/charts-apex-radar',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-radialbar',
                label: 'radialbar',
                link: '/charts-apex-radialbar',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-scatter',
                label: 'scatter',
                link: '/charts-apex-scatter',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-polar-area',
                label: 'polar-area',
                link: '/charts-apex-polar',
                parentKey: 'apexcharts',
              },
              {
                key: 'apexcharts-sparklines',
                label: 'sparklines',
                link: '/charts-apex-sparklines',
                parentKey: 'apexcharts',
              },
            ],
          },
          {
            key: 'chartJS',
            label: 'chartJS',
            collapsed: true,
            parentKey: 'Charts',
            subMenu: [
              {
                key: 'chartJS-area',
                label: 'area',
                link: '/charts-chartjs-area',
                parentKey: 'chartJS',
              },
              {
                key: 'chartJS-bar',
                label: 'bar',
                link: '/charts-chartjs-bar',
                parentKey: 'chartJS',
              },
              {
                key: 'chartJS-line',
                label: 'line',
                link: '/charts-chartjs-line',
                parentKey: 'chartJS',
              },
              {
                key: 'chartJS-other',
                label: 'other',
                link: '/charts-chartjs-other',
                parentKey: 'chartJS',
              },
            ],
          },
        ],
      },
      {
        key: 'tables',
        icon: 'uil-table',
        label: 'tables',
        collapsed: true,
        parentKey: 'components',
        subMenu: [
          {
            key: 'tables-basic',
            label: 'basic-tables',
            link: '/tables-basic',
            parentKey: 'tables',
          },
          {
            key: 'tables-datatables',
            label: 'datatables',
            link: '/tables-datatable',
            parentKey: 'tables',
          },
        ],
      },
      {
        key: 'icons',
        icon: 'uil-streering',
        label: 'icons',
        collapsed: true,
        parentKey: 'components',
        subMenu: [
          {
            key: 'icons-remix',
            label: 'remix',
            link: '/icons-remixicons',
            parentKey: 'icons',
          },
          {
            key: 'icons-material-design',
            label: 'material-design',
            link: '/icons-mdi',
            parentKey: 'icons',
          },
          {
            key: 'icons-unicons',
            label: 'unicons',
            link: '/icons-unicons',
            parentKey: 'icons',
          },
        ],
      },
      {
        key: 'maps',
        icon: 'uil-location-point',
        label: 'maps',
        collapsed: true,
        parentKey: 'components',
        subMenu: [
          {
            key: 'maps-google',
            label: 'google',
            link: '/maps-google',
            parentKey: 'maps',
          },
          {
            key: 'maps-vector',
            label: 'vector',
            link: '/maps-vector',
            parentKey: 'maps',
          },
        ],
      },
    ],
  },
  // {
  //   key: 'layouts',
  //   label: 'layouts',
  //   icon: 'uil-window',
  //   subMenu: [
  //     {
  //       key: 'horizontal',
  //       label: 'horizontal',
  //       link: '/landing',
  //       parentKey: 'layouts',
  //     },
  //     {
  //       key: 'detached',
  //       label: 'detached',
  //       link: '/landing',
  //       parentKey: 'layouts',
  //     },
  //     {
  //       key: 'fullview',
  //       label: 'fullview',
  //       link: '/landing',
  //       parentKey: 'layouts',
  //     },
  //     {
  //       key: 'fullscreen',
  //       label: 'fullscreen',
  //       link: '/landing',
  //       parentKey: 'layouts',
  //     },
  //     {
  //       key: 'hover',
  //       label: 'hover',
  //       link: '/landing',
  //       parentKey: 'layouts',
  //     },
  //     {
  //       key: 'compact',
  //       label: 'compact',
  //       link: '/landing',
  //       parentKey: 'layouts',
  //     },
  //     {
  //       key: 'iconview',
  //       label: 'iconview',
  //       link: '/landing',
  //       parentKey: 'layouts',
  //     },
  //   ],
  // },
]
